[package]
name = "guise-rs"
version = "0.1.0"
authors = ["Alan Beveridge <adgbeveridge@proton.me>"]
description = "Compare faces across images"

repository = "https://github.com/dtolnay/cxx"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
